language: python
python:
  - "3.5"

addons:
  postgresql: "9.6"


install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source='drugs' manage.py test
  - coverage report

after_success:
  - codecov

notifications:
  email: false
