# Generated by Django 2.2.4 on 2019-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='mobile_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
